### ISSUE TITLE
dorkbox.jna.rendering missing

### ISSUE THREAD

**Issue by fusseljoe** [dorkbox/Utilities#10]
Dear Sir or Madam,

I tried to compile the SystemTray-project and I am missing dorkbox.jna.rendering in the package Utilities 1.9. Could you be so kind and either update the package or provide a workaround?

**Comment by dorkbox** [comment]
Hi, at the moment I am currently making changes to the project, and sadly the dorkbox.jna.rendering package is not available yet,

I will be updating everything shortly (I have been working on this over the Christmas holiday), the delay is that there are many sub-projects that need fixing in order to support this (of which, there has been progress fixing them - it’s just slow)

If you need immediate access, I recommend the 3.x release (as it is without JPMS fixes, which ended up being a lot more difficulted than estimated)
